function Hd = disenio_filtro (Fstop1,Fpass1,Fpass2,Fstop2)
%DISENO_FILTRO Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.5 and the DSP System Toolbox 9.0.
% Generated on: 02-Dec-2018 23:49:24

% FIR Window Bandpass filter designed using the FIR1 function.

% All frequency values are in Hz.
Fs = 8000;  % Sampling Frequency

%Fstop1 = 650;             % First Stopband Frequency
%Fpass1 = 694;             % First Passband Frequency
%Fpass2 = 700;             % Second Passband Frequency
%Fstop2 = 733;             % Second Stopband Frequency
Dstop1 = 0.01;            % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.01;            % Second Stopband Attenuation
flag   = 'scale';         % Sampling Flag

% Calculate the order from the parameters using KAISERORD.
[N,Wn,BETA,TYPE] = kaiserord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 ...
                             1 0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Wn, TYPE, kaiser(N+1, BETA), flag);
Hd = dfilt.dffir(b);

% [EOF]
